#!/usr/bin/env python3
"""Anonymized plugin audit dataset for Client A and Client B.
Scores are 1-5, higher = worse (replaceability: higher = easier to remove/replace).
Composite = abandonment + security + performance + replaceability.
"""

import csv, json

# type: free = wordpress.org, premium = paid/commercial, custom = site/agency-specific
# status from live WP-CLI (Client A, prod, 2026-08-05) / DB dump + repo (Client B, dump 2026-02-12)
# last_updated / tested / installs from wordpress.org (fetched 2026-08-05); None = not on wp.org

A = [
    # name, ver, status, type, category, last_upd, tested, installs, ab, sec, pf, rep, flags
    (
        "admin-menu-editor-pro",
        "2.26.1",
        "active",
        "premium",
        "admin-ui",
        None,
        None,
        None,
        2,
        2,
        2,
        4,
        "7 releases behind (2.33.4 available); admin-menu tweaks replaceable with a few lines of code",
    ),
    (
        "advanced-custom-fields",
        "6.8.6",
        "active",
        "free",
        "framework",
        "2026-08-04",
        "7.0.2",
        2000000,
        1,
        1,
        2,
        1,
        "Core dependency; keep",
    ),
    (
        "akismet",
        "5.7",
        "inactive",
        "free",
        "anti-spam",
        "2026-05",
        "7.0.2",
        5000000,
        1,
        1,
        1,
        5,
        "Inactive; comments globally disabled by another plugin — remove",
    ),
    (
        "all-in-one-wp-migration",
        "7.107",
        "inactive",
        "free",
        "backup-migration",
        "2026-07-22",
        "7.0.2",
        5000000,
        1,
        3,
        2,
        5,
        "Inactive; path-traversal CVE fixed in 7.106 (this is 7.107); host provides backups — remove",
    ),
    (
        "allow-multiple-accounts",
        "3.0.4",
        "active",
        "free",
        "users-auth",
        "2015-07-14",
        "4.2.39",
        9000,
        5,
        4,
        1,
        4,
        "Not updated in 11 years, tested to WP 4.2, 9k installs; replace with a small filter",
    ),
    (
        "better-search-replace-pro",
        "1.4.2",
        "inactive",
        "premium",
        "backup-migration",
        None,
        None,
        None,
        3,
        3,
        1,
        5,
        "Inactive; free-version line had unauth PHP object injection (CVE-2023-6933, fixed 1.4.5) — remove; WP-CLI search-replace covers this",
    ),
    (
        "ultimate-branding",
        "3.4.26",
        "active",
        "premium",
        "admin-ui",
        None,
        None,
        None,
        2,
        5,
        3,
        4,
        "URGENT: Branda <= 3.4.29 unauth account takeover (CVE-2026-11551, CVSS 9.8; CVE-2025-14998 exploited in wild). White-labeling replaceable with small custom code",
    ),
    (
        "classic-editor",
        "1.7.0",
        "active",
        "free",
        "editorial",
        "2026-06",
        "7.0.2",
        9000000,
        1,
        1,
        1,
        2,
        "Official; keep while content depends on classic editing",
    ),
    (
        "classic-widgets",
        "0.3",
        "active",
        "free",
        "editorial",
        "2026-01",
        "6.9.5",
        2000000,
        2,
        1,
        1,
        2,
        "Official; keep while SiteOrigin widget areas remain",
    ),
    (
        "code-snippets",
        "3.9.6",
        "active",
        "free",
        "custom-code",
        "2026-07-15",
        "6.9.5",
        1000000,
        1,
        3,
        2,
        2,
        "Stores executable PHP in DB; audit snippets, prefer version-controlled site plugin",
    ),
    (
        "custom-css-js-pro",
        "4.33",
        "inactive",
        "premium",
        "custom-code",
        None,
        None,
        None,
        3,
        2,
        2,
        5,
        "Inactive; all 5 snippets already migrated to child theme — remove and drop license",
    ),
    (
        "disable-comments",
        "2.7.1",
        "active",
        "free",
        "editorial",
        "2026-08-03",
        "7.0.2",
        1000000,
        1,
        1,
        1,
        3,
        "Could be ~20 lines of code, but low cost to keep",
    ),
    (
        "duplicate-page",
        "4.5.9",
        "active",
        "free",
        "editorial",
        "2026-05-08",
        "6.9.5",
        3000000,
        1,
        2,
        1,
        3,
        "Convenience tool; keep or replace with block-editor duplicate",
    ),
    (
        "easy-accordion-pro",
        "2.5.2",
        "inactive",
        "premium",
        "content-widgets",
        None,
        None,
        None,
        2,
        2,
        2,
        3,
        "Deactivated; 40 accordion records / 32 builder usages still need content migration before deletion",
    ),
    (
        "easy-fancybox",
        "2.3.22",
        "active",
        "free",
        "media",
        "2026-06",
        "6.9.4",
        200000,
        1,
        1,
        3,
        4,
        "Front-end JS sitewide; WP 6.4+ core lightbox covers image zoom for most cases",
    ),
    (
        "enable-media-replace",
        "4.2.2",
        "active",
        "free",
        "media",
        "2026-06-28",
        "7.0.2",
        600000,
        1,
        2,
        1,
        2,
        "Useful editorial tool; keep",
    ),
    (
        "genesis-title-toggle",
        "1.9.0",
        "active",
        "free",
        "theme-glue",
        "2017",
        "5.2.24",
        None,
        5,
        2,
        1,
        4,
        "CLOSED on wordpress.org (2024, author request); 8 years old; ~15 lines in the child theme replace it",
    ),
    (
        "gtranslate",
        "3.1.1",
        "active",
        "free",
        "translation",
        "2026-06",
        "7.0.2",
        900000,
        1,
        1,
        3,
        2,
        "External translation service; business decision to keep",
    ),
    (
        "hello-dolly",
        "1.7.2",
        "inactive",
        "free",
        "novelty",
        "2025-10",
        "6.9.5",
        600000,
        1,
        1,
        1,
        5,
        "Ships with WP; remove",
    ),
    (
        "hustle",
        "7.8.8",
        "active",
        "premium",
        "marketing-popups",
        None,
        None,
        None,
        2,
        4,
        3,
        3,
        "3 releases behind: arbitrary file upload + RCE-class fixes land in 7.8.9.3-7.8.11. Only 2 embeds in use; migrate then retire with WPMU DEV stack",
    ),
    (
        "legacy-agency-functions",
        "3.1.1",
        "active",
        "custom",
        "theme-glue",
        None,
        None,
        None,
        5,
        3,
        1,
        3,
        "Legacy agency plugin; vendor acquired twice since install (no update channel)",
    ),
    (
        "legacy-agency-genesis-extend",
        "20200710",
        "active",
        "custom",
        "theme-glue",
        None,
        None,
        None,
        5,
        3,
        2,
        3,
        "Legacy agency plugin, frozen since 2020; enqueues bootstrap + slick sitewide",
    ),
    (
        "legacy-agency-hide-title",
        "1.1",
        "active",
        "custom",
        "theme-glue",
        None,
        None,
        None,
        5,
        3,
        1,
        5,
        "Self-described 'temporary plugin' (2019) still active in prod; ~800 PHP files incl. bundled dev deps for a 1-function fix",
    ),
    (
        "legacy-agency-headers-footers",
        "1.0.1",
        "active",
        "custom",
        "custom-code",
        None,
        None,
        None,
        5,
        3,
        2,
        4,
        "Per-page header/footer injection; overlaps code-snippets + tag manager; ~800 PHP files shipped",
    ),
    (
        "legacy-agency-locations",
        "2.2.1",
        "active",
        "custom",
        "integration",
        None,
        None,
        None,
        5,
        3,
        2,
        3,
        "Maps/listings feature; ~950 PHP files shipped; candidate to fold into site plugin",
    ),
    (
        "legacy-agency-directory",
        "2.8",
        "active",
        "custom",
        "business-critical",
        None,
        None,
        None,
        5,
        3,
        3,
        2,
        "Load-bearing: core directory feature + 3 shortcodes in content. ~1,900 PHP files, ~19MB, ships PHPUnit + composer dev deps to prod",
    ),
    (
        "legacy-agency-responsive-menus",
        "20191220",
        "active",
        "custom",
        "theme-glue",
        None,
        None,
        None,
        5,
        3,
        2,
        3,
        "Frozen since 2019; menu behavior belongs in the theme",
    ),
    (
        "legacy-agency-robots-txt",
        "0.0.1",
        "active",
        "custom",
        "seo",
        None,
        None,
        None,
        5,
        2,
        1,
        4,
        "v0.0.1 robots.txt editor; WP core robots filter or SEO plugin covers this",
    ),
    (
        "legacy-agency-shortcodes",
        "1.0.4",
        "active",
        "custom",
        "content-widgets",
        None,
        None,
        None,
        5,
        3,
        2,
        3,
        "Shortcode set overlapping Shortcodes Ultimate; ~800 PHP files shipped",
    ),
    (
        "legacy-agency-siteorigin-blocks",
        "0.2.1",
        "active",
        "custom",
        "page-builder",
        None,
        None,
        None,
        5,
        3,
        2,
        3,
        "SiteOrigin customizations; retires with the SiteOrigin stack",
    ),
    (
        "imagify",
        "2.3.x",
        "active",
        "free",
        "media",
        "2026-07-29",
        "7.0.2",
        1000000,
        1,
        1,
        2,
        2,
        "Image optimization; evaluate vs host-level optimization",
    ),
    (
        "livemesh-siteorigin-widgets",
        "3.9.2",
        "active",
        "free",
        "page-builder",
        "2025-12",
        "6.8.5",
        None,
        4,
        4,
        3,
        3,
        "CLOSED on wordpress.org 2026-05-18 pending full review — no update channel while closed; audit which widgets are used",
    ),
    (
        "client-a-custom",
        "0.1.0",
        "active",
        "custom",
        "business-critical",
        None,
        None,
        None,
        1,
        1,
        1,
        1,
        "Current agency's site plugin (custom interactive feature); the consolidation target",
    ),
    (
        "onelogin-saml-sso",
        "3.6.0",
        "active",
        "free",
        "users-auth",
        "2026-07-01",
        "5.9.13",
        7000,
        3,
        2,
        1,
        2,
        "Patched against the 9.1 auth bypass (fixed 3.6.0) but only tested to WP 5.9; community-maintained after two corporate acquisitions; SSO is business-critical",
    ),
    (
        "siteorigin-panels",
        "2.35.0",
        "active",
        "free",
        "page-builder",
        "2026-07-01",
        "7.0.1",
        400000,
        1,
        1,
        3,
        2,
        "Page layouts depend on panels_data; long-term migration only",
    ),
    (
        "popover",
        "4.8.1",
        "inactive",
        "premium",
        "marketing-popups",
        None,
        None,
        None,
        5,
        3,
        2,
        5,
        "PopUp Pro — product discontinued by vendor in 2019 (folded into Hustle); inactive; remove",
    ),
    (
        "redirection",
        "5.9.0",
        "active",
        "free",
        "seo",
        "2026-07-11",
        "7.0.2",
        2000000,
        1,
        1,
        2,
        2,
        "Current, clean record; keep",
    ),
    (
        "shortcodes-ultimate",
        "7.8.4",
        "active",
        "free",
        "content-widgets",
        "2026-07",
        "7.0.1",
        400000,
        1,
        2,
        3,
        2,
        "145+ meta rows and 53 custom shortcodes locked in content — removal is a content-migration project",
    ),
    (
        "shortcodes-ultimate-maker",
        "1.5.15",
        "active",
        "premium",
        "content-widgets",
        None,
        None,
        None,
        3,
        2,
        1,
        3,
        "Paid add-on; retires when the 53 custom shortcodes migrate",
    ),
    (
        "siteorigin-premium",
        "1.76.0",
        "active",
        "premium",
        "page-builder",
        None,
        None,
        None,
        1,
        1,
        2,
        4,
        "License paid for one addon (toggle visibility); replace addon with code, drop license",
    ),
    (
        "so-widgets-bundle",
        "1.74.2",
        "active",
        "free",
        "page-builder",
        "2026-07",
        "6.9.4",
        400000,
        1,
        1,
        3,
        2,
        "Widget areas depend on it; retires with SiteOrigin stack",
    ),
    (
        "addon-so-widgets-bundle",
        "2.4.2",
        "active",
        "free",
        "page-builder",
        "2019",
        "5.2.24",
        7000,
        5,
        3,
        2,
        4,
        "Author states no longer developed; 7 years stale, tested to WP 5.2; audit usage and remove",
    ),
    (
        "unconfirmed",
        "1.3.7",
        "inactive",
        "free",
        "users-auth",
        "2022",
        "6.4.8",
        1000,
        4,
        2,
        1,
        5,
        "Multisite activation tool, inactive, 1k installs; remove",
    ),
    (
        "user-role-editor-pro",
        "4.64.4",
        "active",
        "premium",
        "users-auth",
        None,
        None,
        None,
        2,
        3,
        1,
        3,
        "Free line had CSRF->privesc <=4.64.3 (CVE-2024-12293); pro 4.64.4 patch status unconfirmed — verify. Role tweaks could be code",
    ),
    (
        "niche-vendor-embeds",
        "1.4.x",
        "active",
        "free",
        "business-critical",
        "2025",
        "6.1.10",
        200,
        4,
        2,
        2,
        2,
        "Third-party media embeds from a niche vendor; ~200 installs, tested to WP 6.1 — niche but business-critical; monitor",
    ),
    (
        "wordpress-importer",
        "0.9.5",
        "inactive",
        "free",
        "dev-tools",
        "2025-11",
        "6.8.6",
        2000000,
        1,
        1,
        1,
        5,
        "One-off tool; remove until needed",
    ),
    (
        "wp-2fa-premium",
        "3.1.1.2",
        "active",
        "premium",
        "users-auth",
        None,
        None,
        None,
        1,
        1,
        1,
        3,
        "2FA policy currently do-not-enforce; decide policy or replace with free tier/SSO enforcement",
    ),
    (
        "wp-carousel-pro",
        "3.10.3",
        "inactive",
        "premium",
        "content-widgets",
        None,
        None,
        None,
        2,
        2,
        2,
        5,
        "Inactive; its settings still autoload and its weekly cron still fires — remove and clean up",
    ),
    (
        "wp-mail-smtp",
        "4.9.0",
        "active",
        "free",
        "email",
        "2026-07",
        "7.0.2",
        4000000,
        1,
        1,
        1,
        2,
        "Deliverability; keep",
    ),
    (
        "wpmudev-updates",
        "5.0.0",
        "active",
        "premium",
        "vendor-dashboard",
        None,
        None,
        None,
        2,
        2,
        2,
        3,
        "WPMU DEV dashboard; only needed to license Hustle/Branda — falls away if that stack retires",
    ),
    (
        "wp-rocket",
        "3.23.1",
        "active",
        "premium",
        "caching-performance",
        None,
        None,
        None,
        1,
        1,
        1,
        2,
        "Primary page cache; performing well; keep",
    ),
    (
        "wpshapere",
        "6.1.20",
        "active",
        "premium",
        "admin-ui",
        None,
        None,
        None,
        3,
        2,
        2,
        4,
        "Admin theme 2 major versions behind (v8 current); overlaps Branda; replace both with ~50 lines of branding code",
    ),
    (
        "wordpress-seo",
        "28.1",
        "active",
        "free",
        "seo",
        "2026-08-04",
        "7.0.2",
        10000000,
        1,
        1,
        2,
        1,
        "Yoast, current (28.1 fixes the recent stored-XSS line); keep",
    ),
]

A_MU = [
    (
        "host-mu-plugins",
        "3.6.1",
        "must-use",
        "host",
        "hosting",
        "Managed host platform mu-plugin",
    )
]
A_DROPINS = ["advanced-cache.php (WP Rocket)"]

B = [
    (
        "advanced-custom-fields",
        "6.7.0",
        "active",
        "free",
        "framework",
        "2026-08-04",
        "7.0.2",
        2000000,
        1,
        1,
        2,
        1,
        "Core dependency; keep (update: repo one minor behind)",
    ),
    (
        "akeebabackupwp",
        "9.0.6",
        "active",
        "free",
        "backup-migration",
        "2026-07-29",
        None,
        None,
        2,
        2,
        2,
        3,
        "Distributed by vendor, not wp.org (no wp-admin update visibility); 9.1.8 current; deployment extractor script left in webroot — delete it",
    ),
    (
        "app-for-cf",
        "1.9.6.2",
        "active",
        "free",
        "caching-performance",
        "2026-04-28",
        "7.0.2",
        1000,
        2,
        2,
        2,
        3,
        "Cloudflare control incl. edge caching; 1k installs; overlaps local page cache — pick one caching owner",
    ),
    (
        "backwpup",
        "5.6.1",
        "inactive",
        "free",
        "backup-migration",
        "2026-07-21",
        "7.0.2",
        400000,
        1,
        2,
        1,
        5,
        "Inactive second backup plugin (Akeeba active); remove",
    ),
    (
        "category-redirect",
        "1.0",
        "active",
        "custom",
        "seo",
        None,
        None,
        None,
        4,
        3,
        2,
        5,
        "Single-file custom redirect logic parsing category descriptions; Redirection plugin (installed) already does this",
    ),
    (
        "changemaker",
        "1.0",
        "inactive",
        "custom",
        "editorial",
        None,
        None,
        None,
        4,
        3,
        1,
        5,
        "Custom staging/publishing tool, inactive; remove",
    ),
    (
        "easy-notification-bar",
        "1.6.1",
        "active",
        "free",
        "content-widgets",
        "2026-03-10",
        "6.9.5",
        9000,
        2,
        1,
        2,
        3,
        "9k installs; a notice bar is ~30 lines in the theme or a design-system component",
    ),
    (
        "elementor-custom-query",
        "1.0",
        "active",
        "custom",
        "page-builder",
        None,
        None,
        None,
        4,
        2,
        1,
        3,
        "Single-file loop-grid filter; fold into site core plugin",
    ),
    (
        "elementor-pro",
        "3.33.2",
        "active",
        "premium",
        "page-builder",
        None,
        None,
        None,
        1,
        2,
        3,
        2,
        "Theme builder + forms capability; part of platform",
    ),
    (
        "elementor",
        "3.33.4",
        "active",
        "free",
        "page-builder",
        "2026-07-28",
        "7.0.2",
        10000000,
        1,
        3,
        3,
        1,
        "Platform. But 3.33.4 predates fixes now in 4.x line (stored XSS/priv-esc CVE-2026-6127 fixed 4.0.5) — upgrade path needed",
    ),
    (
        "events-address-fixer",
        "1.0",
        "active",
        "custom",
        "integration",
        None,
        None,
        None,
        4,
        2,
        1,
        5,
        "Fixes addresses for The Events Calendar — which is no longer installed. Dead code, active; remove",
    ),
    (
        "forminator",
        "1.49.0",
        "active",
        "free",
        "forms",
        "2026-07-30",
        "7.0.2",
        600000,
        1,
        4,
        2,
        2,
        "7 releases behind: unauth file-read + stored-XSS fixes land in 1.55.x-1.56.2; update urgently. Overlaps Elementor Pro forms",
    ),
    (
        "frameworkdeps",
        "1.0",
        "active",
        "custom",
        "custom-code",
        None,
        None,
        None,
        4,
        3,
        4,
        4,
        "'Injects all framework dependencies' — 12 scripts + 6 styles enqueued sitewide (validationEngine, bootstrap-waitingfor); classic every-page-load anti-pattern",
    ),
    (
        "gmap-block",
        "1.1.0",
        "active",
        "free",
        "content-widgets",
        "2026-03-24",
        "6.9.5",
        10000,
        2,
        2,
        2,
        3,
        "Maps block; third mapping approach on this site (uninstalled WP Go Maps options remain); consolidate",
    ),
    (
        "gtranslate",
        "3.0.9",
        "active",
        "free",
        "translation",
        "2026-06",
        "7.0.2",
        900000,
        1,
        1,
        3,
        2,
        "External translation service; keep by business decision",
    ),
    (
        "headers-security-advanced-hsts-wp",
        "5.2.4",
        "active",
        "free",
        "security",
        "2026-07-07",
        "7.0.2",
        90000,
        2,
        2,
        2,
        4,
        "Security headers belong at the edge (Cloudflare — already managed by app-for-cf) or server config",
    ),
    (
        "client-b-content-hub-results",
        "1.0",
        "active",
        "custom",
        "business-critical",
        None,
        None,
        None,
        4,
        3,
        1,
        2,
        "Content-hub search results; keep function, fold into site core plugin",
    ),
    (
        "client-b-content-hub-search",
        "1.0",
        "active",
        "custom",
        "business-critical",
        None,
        None,
        None,
        4,
        3,
        1,
        2,
        "Content-hub search widget; fold into site core plugin",
    ),
    (
        "hello-dolly",
        "1.7.2",
        "inactive",
        "free",
        "novelty",
        "2025-10",
        "6.9.5",
        600000,
        1,
        1,
        1,
        5,
        "Remove",
    ),
    (
        "hook-profiler",
        "1.0.0",
        "inactive",
        "custom",
        "dev-tools",
        None,
        None,
        None,
        3,
        2,
        1,
        5,
        "Profiling tool in production plugin dir, inactive; remove from prod",
    ),
    (
        "client-b-saas-search",
        "1.0",
        "active",
        "custom",
        "integration",
        None,
        None,
        None,
        4,
        2,
        1,
        2,
        "Third-party search SaaS embed shortcode; fold into site core plugin",
    ),
    (
        "lightweight-accordion",
        "1.6.0",
        "active",
        "free",
        "content-widgets",
        "2026-07-24",
        "7.0.2",
        10000,
        1,
        1,
        1,
        4,
        "Third accordion implementation available on this site; WP core Details block (6.3+) covers most cases",
    ),
    (
        "limit-login-attempts-reloaded",
        "2.26.26",
        "inactive",
        "free",
        "security",
        "2026-07-08",
        "7.0.2",
        1000000,
        1,
        2,
        1,
        3,
        "Brute-force protection installed but DEACTIVATED — either activate or remove and rely on edge/WAF",
    ),
    (
        "mobilesearch",
        "1.1",
        "active",
        "custom",
        "content-widgets",
        None,
        None,
        None,
        4,
        2,
        1,
        4,
        "Mobile search popup; belongs in the theme/design system",
    ),
    (
        "phpengine",
        "1.0",
        "active",
        "custom",
        "custom-code",
        None,
        None,
        None,
        4,
        5,
        2,
        4,
        "'Runs PHP pages as menu items' — arbitrary-PHP-execution pattern, single file, active in prod; highest-priority custom plugin to retire",
    ),
    (
        "post-type-switcher",
        "4.0.1",
        "active",
        "free",
        "editorial",
        "2026-03-24",
        "6.9.5",
        200000,
        1,
        2,
        1,
        4,
        "Admin one-off tool; deactivate between uses",
    ),
    (
        "redirection",
        "5.5.2",
        "active",
        "free",
        "seo",
        "2026-07-11",
        "7.0.2",
        2000000,
        2,
        1,
        2,
        2,
        "Solid; 5.9.0 current — update; absorb category-redirect into it",
    ),
    (
        "redis-cache",
        "2.7.0",
        "active",
        "free",
        "caching-performance",
        "2026-05-04",
        "7.0.2",
        400000,
        1,
        1,
        1,
        2,
        "Object cache + dropin; legitimate pairing with a page cache; keep",
    ),
    (
        "replace-http-with-https",
        "1.2",
        "active",
        "custom",
        "custom-code",
        None,
        None,
        None,
        4,
        2,
        3,
        5,
        "Rewrites http->https in content on every request; run a one-time DB search-replace and remove",
    ),
    (
        "shortcodes-ultimate",
        "7.4.7",
        "active",
        "free",
        "content-widgets",
        "2026-07",
        "7.0.1",
        400000,
        1,
        4,
        3,
        2,
        "4 stored-XSS fixes land in 7.4.8-7.5.0; update. Shortcodes locked in content",
    ),
    (
        "show-current-template",
        "0.5.3",
        "inactive",
        "free",
        "dev-tools",
        "2026-06-04",
        "7.0.2",
        100000,
        1,
        1,
        1,
        5,
        "Dev tool, inactive; remove from prod",
    ),
    (
        "client-b-block-api",
        "1.0",
        "active",
        "custom",
        "security",
        None,
        None,
        None,
        4,
        2,
        1,
        3,
        "Blocks unauthenticated REST access; keep function, fold into site core plugin",
    ),
    (
        "client-b-breadcrumbs",
        "1.8",
        "active",
        "custom",
        "seo",
        None,
        None,
        None,
        4,
        2,
        1,
        4,
        "Yoast (installed) ships breadcrumbs; consolidate",
    ),
    (
        "client-b-cta",
        "1.0",
        "active",
        "custom",
        "content-widgets",
        None,
        None,
        None,
        4,
        2,
        1,
        3,
        "CTA injection into Elementor headers; fold into site core plugin",
    ),
    (
        "client-b-posts-in-cat",
        "1.0",
        "active",
        "custom",
        "content-widgets",
        None,
        None,
        None,
        4,
        2,
        1,
        3,
        "Category article list shortcode; fold into site core plugin",
    ),
    (
        "client-b-schema",
        "0.2.1",
        "active",
        "custom",
        "seo",
        None,
        None,
        None,
        4,
        3,
        1,
        4,
        "Disables Yoast schema and takes over — two schema systems to reason about; pick one",
    ),
    (
        "client-b-tel-click",
        "1.0",
        "active",
        "custom",
        "content-widgets",
        None,
        None,
        None,
        4,
        2,
        3,
        4,
        "Regex-rewrites phone numbers on every page render; theme filter or edge rule instead",
    ),
    (
        "client-b-theme-selector",
        "1.0",
        "active",
        "custom",
        "page-builder",
        None,
        None,
        None,
        4,
        2,
        1,
        3,
        "Custom Elementor display conditions; fold into site core plugin",
    ),
    (
        "client-b-toc",
        "1.0",
        "active",
        "custom",
        "content-widgets",
        None,
        None,
        None,
        4,
        2,
        1,
        3,
        "Alphabetical index shortcode; fold into site core plugin",
    ),
    (
        "client-b-core",
        "0.1.0",
        "inactive",
        "custom",
        "business-critical",
        None,
        None,
        None,
        1,
        1,
        1,
        1,
        "New agency redesign content model — the consolidation target (not yet activated)",
    ),
    (
        "client-b-elementor-components",
        "0.1.0",
        "inactive",
        "custom",
        "page-builder",
        None,
        None,
        None,
        1,
        1,
        1,
        1,
        "New agency design-system components (redesign in progress)",
    ),
    (
        "user-role-editor",
        "4.64.6",
        "active",
        "free",
        "users-auth",
        "2026-05-21",
        "7.0.2",
        700000,
        1,
        2,
        1,
        3,
        "Patched past CVE-2024-12293 (<=4.64.3); audit whether still needed post-redesign",
    ),
    (
        "wordpress-importer",
        "0.9.5",
        "inactive",
        "free",
        "dev-tools",
        "2025-11",
        "6.8.6",
        2000000,
        1,
        1,
        1,
        5,
        "One-off tool; remove until needed",
    ),
    (
        "wordpress-seo",
        "26.5",
        "active",
        "free",
        "seo",
        "2026-08-04",
        "7.0.2",
        10000000,
        1,
        3,
        2,
        1,
        "Yoast 26.5: two stored-XSS advisories fixed by 26.9/28.1 — update; keep as the single SEO owner",
    ),
    (
        "wp-cli-login-server",
        "1.5",
        "active",
        "custom",
        "dev-tools",
        None,
        None,
        None,
        3,
        4,
        1,
        5,
        "Magic-login-link companion ACTIVE in production; deactivate outside deploy windows",
    ),
    (
        "wp-codespace",
        "-",
        "inactive",
        "custom",
        "dev-tools",
        None,
        None,
        None,
        3,
        1,
        1,
        5,
        "Empty plugin folder (0 PHP files); delete",
    ),
    (
        "wp-super-cache",
        "3.0.3",
        "active",
        "free",
        "caching-performance",
        "2026-05-27",
        "7.0.2",
        1000000,
        1,
        1,
        1,
        2,
        "Page cache, clean record at this version; but site also carries W3TC, LiteSpeed and Docket Cache remnants + Cloudflare edge — one owner needed",
    ),
]

B_MU = [
    (
        "akeeba-backup-coreupdate",
        "-",
        "must-use",
        "custom",
        "backup-migration",
        "Akeeba core-update glue",
    ),
    (
        "elementor-safe-mode",
        "-",
        "must-use",
        "free",
        "page-builder",
        "Elementor troubleshooting leftover",
    ),
]
B_DROPINS = [
    "advanced-cache.php (WP Super Cache)",
    "object-cache.php (Redis)",
    "maintenance.php (custom)",
]


def rows(site, data):
    out = []
    for name, ver, status, typ, cat, upd, tested, inst, ab, sec, pf, rep, flags in data:
        comp = ab + sec + pf + rep
        out.append(
            dict(
                site=site,
                plugin=name,
                version=ver,
                status=status,
                type=typ,
                category=cat,
                wporg_last_updated=(
                    upd or "n/a (not on wp.org)" if typ in ("free",) else (upd or "n/a")
                ),
                wporg_tested=tested or "-",
                active_installs=inst if inst is not None else "-",
                abandonment=ab,
                security=sec,
                performance=pf,
                replaceability=rep,
                composite=comp,
                notes=flags,
            )
        )
    return out


allrows = rows("Client A", A) + rows("Client B", B)

with open("../data/plugin-inventory.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(allrows[0].keys()))
    w.writeheader()
    w.writerows(allrows)

risk = sorted(allrows, key=lambda r: -r["composite"])
with open("../data/risk-matrix.csv", "w", newline="") as f:
    w = csv.DictWriter(
        f,
        fieldnames=[
            "site",
            "plugin",
            "version",
            "status",
            "type",
            "abandonment",
            "security",
            "performance",
            "replaceability",
            "composite",
            "notes",
        ],
        extrasaction="ignore",
    )
    w.writeheader()
    w.writerows(risk)


def stats(site, data):
    act = [p for p in data if p[2] == "active"]
    ina = [p for p in data if p[2] == "inactive"]
    prem = [p for p in data if p[3] == "premium"]
    cust = [p for p in data if p[3] == "custom"]
    free = [p for p in data if p[3] == "free"]
    high = [p for p in data if (p[8] + p[9] + p[10] + p[11]) >= 13]
    return dict(
        site=site,
        total=len(data),
        active=len(act),
        inactive=len(ina),
        premium=len(prem),
        custom=len(cust),
        free=len(free),
        high_risk=len(high),
    )


s = dict(A=stats("Client A", A), B=stats("Client B", B))
s["A"]["mu"] = 1
s["B"]["mu"] = 2
print(json.dumps(s, indent=1))
print("top12 risk:")
for r in risk[:12]:
    print(
        f'  {r["site"]}: {r["plugin"]} {r["composite"]} ({r["abandonment"]}/{r["security"]}/{r["performance"]}/{r["replaceability"]})'
    )
print("rows:", len(allrows))
